version: '3.6'
services:
  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    hostname: 'gitlab.example.com'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        #external_url 'https://gitlab.example.com'
        gitlab_rails['initial_root_password'] = 'bhMHcW3dkfcb'
        gitlab_rails['registry_enabled'] = true
        gitlab_rails['registry_host'] = "${ipaddr}"
        gitlab_rails['registry_port'] = "5005"
        letsencrypt['enable'] = true
        # Add any other gitlab.rb configuration here, each on its own line
    ports:
      - '80:80'
      # - '443:443'
      - '2222:22'
      - '5005:5005'
    networks:
      vpcbr:
        ipv4_address: 10.5.0.5
    volumes:
      - '/srv/gitlab/config:/etc/gitlab'
      - '/srv/gitlab/logs:/var/log/gitlab'
      - '/srv/gitlab/data:/var/opt/gitlab'
    shm_size: '256m'
  gitlab-runner:
    image: 'gitlab/gitlab-runner:latest'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - runner-config:/etc/gitlab-runner
    restart: unless-stopped
  tor:
    build: .
    volumes:
      # - ./torrc:/etc/tor/torrc ro
      - ./hidden:/var/lib/tor/hidden_service
    ports:
      #- "80:80"
      - "443:443"
    depends_on:
      - gitlab
    networks:
      vpcbr:
        ipv4_address: 10.5.0.6
    links:
      - gitlab
volumes:
  runner-config:
  hidden:
networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1
